### ISSUE TITLE
Unit conversion bug

### ISSUE THREAD

**Issue by savvyscientist** [Rich4ever11/regridding_dataset#10]
https://github.com/Rich4ever11/regridding_dataset/blob/f18f9c6b3747d48cddbeed3254846966375b83cb/wglc_script.py#L110
This should be dividing by the number of seconds in a day: density_variable_data[month] / DAYS_TO_SECONDS

**Comment by Rich4ever11** [comment]
fixed in commit. Change can be found [here](https://github.com/Rich4ever11/regridding_dataset/blob/3c757b77d7e82c5d5f7843adf5b35c3e00e74943/wglc_script.py#L100).
